name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR and Release
    run-on: ubuntu-latest
    steps:
      # 拉main分支代码
      - name: git pull branch main
        uses: actions/checkout@main
      # 设置pnpm
      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: ^9.0.0
      # 设置node
      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          version: 20.x
          cache: pnpm
      # 安装依赖
      - name: install dependencies
        run: pnpm install
      # 检测changesets 并且发布
      - name: create release pr and publish
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
